language: android
sudo: true
jdk:
- oraclejdk8

android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.2
  - android-25
  - extra-android-m2repository

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - deadsnakes
    packages:
    - python3.5
    - libstdc++-4.9-dev

before_install:
- wget https://dependencies.vcmi.download/android/ext-output.zip
- unzip ext-output.zip
- . ./CI/android_licenses_fix.sh
- git clone https://github.com/urho3d/android-ndk.git $HOME/android-ndk-root
- export ANDROID_NDK_HOME=$HOME/android-ndk-root
- python3.5 ./CI/create_travis_conf.py
- wget -O ./boost.tar.gz https://dl.bintray.com/boostorg/release/1.64.0/source/boost_1_64_0.tar.gz
- mkdir -p ext/boost/
- tar xzvf boost.tar.gz -C ./ext/boost/ >/dev/null
- chmod +x ./project/gradlew
- git submodule update --remote $TRAVIS_BUILD_DIR/ext/vcmi
script:
- python3.5 ./build.py fixpaths
- python3.5 ./build.py build-cmake
- python3.5 ./build.py build-app

after_success:
- . $TRAVIS_BUILD_DIR/CI/upload_package.sh

notifications:
  slack:
    secure: lH+q+gQaagFpl98uDBNwG6c7V0p9sqkCFIb7i/grHo14f6AAshcxPnQQhOzphfrT2y0aJapx7p89IuqfaDXl716r3NgDQ7GnZnsK4kcuX5qRthMw14wWGVl5RdOqljG5w5t2bBedumSHZ7IuxL5Y2pQeZ+myauW6Usi6lfGckpajOrt5q/uKpgVZXnvampSCvnOKc3bID1O846on7GHeUIYxLHrmkzG3VlByJBa2Tq/xle1oXBG69U1tynl+Qpvr/3xRrgnloplmhaZpS75ku1PnLtcGqu42vviMW73qy3yk8IgXCWqhEtfZh3AMhx/Yo2eamtMTc++URPV8DR/aygt9KPeR8wjncdXwrYEdR3aU1Yh9BJPK3AybXUMZMOta/czf+Hkv0aaBacD463F0A+DDpizkVGs+gq5IMs9xlO1voXsnSHNNs1e6RmqY1qmY36RXFmN5q/Arcvpc+klPmZ+PxHwpqS2vlDRR3gzEWSbLB7HbdczXxTK63q41LJAdajK5NCEVzhmBS8NmlxuOU5uJPVjiCArxG6vxlcHOq7DXDUkYOisPbutsa1PM+33+GqX7nT1M8TYa0iRCDz2NcpSv/Xck6FJDt/gMcA96e+5+PWLcFGvBqmTUneYNMXNAjZewCaGqXIf1TTz9BRz97vueFAP3UX7bbKTInFlJONA=
